/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class CodeIndex {
  static open(options: OpenIndexOptions): Promise<CodeIndex>
  status(): Promise<IndexStatus>
  beginGeneration(options: StartIndexOptions): Promise<IndexGenerationHandle>
  runStructuralExtraction(generationId: string): Promise<void>
  nextEmbeddingBatch(generationId: string, limit: number): Promise<Array<EmbeddingBatchItem>>
  putEmbeddings(generationId: string, values: Array<EmbeddingResult>, dimensions: number): Promise<void>
  commitIndex(generationId: string): Promise<void>
  failIndex(generationId: string, reason: string): Promise<void>
  heartbeatLease(): Promise<void>
  search(input: SearchInput): Promise<Array<SearchHit>>
  findSymbol(input: FindSymbolInput): Promise<Array<SymbolHit>>
  callers(input: TraversalInput): Promise<Array<SymbolHit>>
  callees(input: TraversalInput): Promise<Array<SymbolHit>>
  exploreSymbol(input: ExploreSymbolInput): Promise<ExploreResult>
}

export interface EmbeddingBatchItem {
  id: number
  text: string
}

export interface EmbeddingResult {
  id: number
  vector: Array<number>
}

export interface ExploreResult {
  nodes: Array<SymbolHit>
  edges: Array<GraphEdgeHit>
}

/** No core counterpart — see `FindSymbolInput`. */
export interface ExploreSymbolInput {
  nodeId: string
  callersDepth?: number
  calleesDepth?: number
  limit?: number
}

/** No core counterpart — `store::graph::find_symbol` takes plain fields, not this struct. */
export interface FindSymbolInput {
  term: string
  limit?: number
}

export interface GraphEdgeHit {
  source: string
  target: string
  relation: string
}

export interface IndexGenerationHandle {
  generationId: string
}

export interface IndexStats {
  files: number
  chunks: number
  nodes: number
  edges: number
}

export interface IndexStatus {
  /** `never_ran | in_progress | done | failed`. */
  state: string
  usable: boolean
  stale: boolean
  staleReasons: Array<string>
  repoKey: string
  databasePath: string
  revision: RevisionInfo
  stats: IndexStats
}

/** No core counterpart — only ever constructed inside `lib.rs` from `repository::inspect`'s result. */
export interface OpenIndexOptions {
  repository: string
  database: string
}

/**
 * Resolves repository identity without an open `CodeIndex` — a caller needs `repoKey` to build a
 * storage path before it knows what to pass to `CodeIndex.open()`.
 */
export declare function repositoryIdentity(repositoryRoot: string): Promise<RepositoryIdentity>

/** No core counterpart — only ever constructed inside `lib.rs` from `repository::inspect`'s result. */
export interface RepositoryIdentity {
  repoKey: string
  canonicalRoot: string
  headSha: string
  dirty: boolean
  remoteIdentity?: string
}

export interface RevisionInfo {
  indexedHeadSha?: string
  currentHeadSha: string
  dirty: boolean
}

export interface SearchHit {
  chunkId: number
  nodeId?: string
  symbolName?: string
  filePath: string
  startLine: number
  endLine: number
  content: string
  /** Cosine similarity, higher is more relevant. */
  score: number
}

export interface SearchInput {
  vector: Array<number>
  limit?: number
  path?: string
  language?: string
}

export interface StartIndexOptions {
  /** Identifies the embedding model/config in use. `None` means this generation is structural only. */
  embeddingFingerprint?: string
  embeddingDimensions?: number
}

export interface SymbolHit {
  nodeId: string
  label: string
  sourceFile: string
  startLine: number
}

/** No core counterpart — see `FindSymbolInput`. */
export interface TraversalInput {
  nodeId: string
  limit?: number
}
